#!/bin/sh

# VARS

VERSION=0.0.1
CONFIG=~/.config/taskshrc
DEFAULT_FOLDER=~/tasksh

NAME=$(basename "$0")

if [ -f $CONFIG ]; then
    # shellcheck disable=SC1090
    . $CONFIG
else
    touch $CONFIG
fi

# functions

# shellcheck disable=SC2120
help() {

    WHICH=${1:-general}

    case "$WHICH" in

        general )
            echo "Usage: $NAME [mode] [OPTIONS]..."
            echo "Manage (add, edit, view, etc.) tasks."
            echo 
            echo "$NAME has 8 modes, (a)dd, (ag)enda, (c)onfig, (d)one, (e)dit, (l)ist,"
            echo "(r)emove, and (v)iew."
            echo "Each mode has different functionality, to see usage for use:"
            echo "  $NAME [mode] -h"
            echo "  or"
            echo "  $NAME [mode] --help"
            echo
            echo "For example:"
            echo "  $NAME add -h"
            echo "  or for using the add shorthand"
            echo "  $NAME a -h"
            echo
            echo "There is technically a 9th 'no-mode' mode with two options:"
            echo
            echo "Help:"
            echo "  This gets the general help message for $NAME"
            echo
            echo "  $NAME -h"
            echo "  $NAME --help"
            echo 
            echo "Version:"
            echo "  This gets the $NAME version"
            echo
            echo "  $NAME -v"
            echo "  $NAME --version"

        ;;

        add )
            echo "Usage: $NAME add [OPTIONS]... [DESCRIPTION]"
            echo "Add a task."
            echo 
            # TODO add remaining docs
        ;;

        agenda )
            echo "Usage: $NAME agenda [OPTIONS]..."
            echo "View your agenda generated based on tasks"
            echo 
            # TODO add remaining docs
        ;;

        config ) 
            echo "Usage: $NAME config [OPTIONS]..."
            echo "Edit $NAME configuration"
            echo 
            # TODO add remaining docs
        ;;

        mark_done )
            echo "Usage:     $NAME done [TASK_ID] [OPTIONS]..."
            echo "Alternate: $NAME done [OPTIONS]..."
            echo "Mark a task as done."
            echo 
            # TODO add remaining docs
        ;; 

        edit )
            echo "Usage:     $NAME edit [TASK_ID] [OPTIONS]..."
            echo "Alternate: $NAME edit [OPTIONS]..."
            echo "Edits an existing task."
            echo 
            # TODO add remaining docs
        ;;

        list )
            echo "Usage: $NAME list [OPTIONS]..."
            echo "List tasks."
            echo 
            # TODO add remaining docs
        ;;

        remove )
            echo "Usage:     $NAME remove [TASK_ID] [OPTIONS]..."
            echo "Alternate: $NAME remove [OPTIONS]..."
            echo "Removes a task"
            echo 
            # TODO add remaining docs
        ;;

        view )
            echo "Usage:     $NAME view [TASK_ID] [OPTIONS]..."
            echo "Alternate: $NAME view [OPTIONS]..."
            echo "View a task."
            echo 
            # TODO add remaining docs
        ;;
        
        * )
            echo "Unknown help section, ERROR"
            exit 1
    esac

    exit 0
}

default() {
    echo TASKSH v$VERSION

    help
}

configure() {
    # check notes dir
    if [ -z ${TASKSH_DIR+x} ]; then
        echo "TASHSH has no folder set."

        echo "Specify a folder TASKSH should use to store data [$DEFAULT_FOLDER]: " 
        read -r FOLDER
        TASKSH_DIR=${FOLDER:-$DEFAULT_FOLDER}

        if [ ! -d "$TASKSH_DIR" ]; then
            create_tasksh_dir

        elif [ "$(ls -A "$TASKSH_DIR")" ]; then
            echo "$TASKSH_DIR is not empty, are you sure you want to use this folder? y/[n]"

            while true; do
                read -r YN
                case "${YN:-n}" in
                    y ) 
                        echo "Successfully created TASKSH folder ($TASKSH_DIR)"
                        if echo "TASKSH_DIR=\"$TASKSH_DIR\"" >> $CONFIG; then
                            echo "Successfully added TASKSH_DIR to TASKSH config"
                        else
                            echo "FAILED to add TASKSH_DIR to TASKSH config"
                            exit 1
                        fi

                        break
                        ;;

                    n ) 
                        echo "TASKSH requires a folder to function, exiting"

                        exit 1
                        ;;

                    * ) echo "Invalid response, input y or n";;
                esac
            done
        fi
    fi

    if [ ! -d "$TASKSH_DIR" ]; then
        create_tasksh_dir
    fi
}

create_tasksh_dir() {
    echo "$TASKSH_DIR does not exist, would you like to create it y/[n]"
            
    while true; do
        read -r YN
        case "${YN:-n}" in
            y ) 
                if mkdir -p "$TASKSH_DIR"; then
                    echo "Successfully created TASKSH folder ($TASKSH_DIR)"
                    if echo "TASKSH_DIR=\"$TASKSH_DIR\"" >> $CONFIG; then
                        echo "Successfully added TASKSH_DIR to TASKSH config"
                    else
                        echo "FAILED to add TASKSH_DIR to TASKSH config"
                        exit 1
                    fi
                else
                    echo "FAILED TO create TASKSH folder ($TASKSH_DIR)"
                    exit 1
                fi

                break
                ;;

            n ) 
                echo "TASKSH requires a folder to function, exiting"

                exit 1
                ;;

            * ) echo "Invalid response, input y or n";;
        esac
    done
}

# Handle configuration
configure

# Mode functions
add() {
    shift # shift over mode

    SHORT=d:s:l:t:c:ea:ph 
    LONG=due:,schedule:,loop:,type:,desc:,editor,assign_parent:,parent_selector,help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help add
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in 

        -d | --due )  # TODO
            echo due placeholder
            echo $2
            shift 2
            ;;

        -s | --schedule ) # TODO
            echo schedule placeholder
            shift 2
            ;;

        -l | --loop ) # TODO
            echo loop placeholder
            echo $2
            shift 2
            ;;

        -t | --type ) # TODO
            echo "type placeholder"
            ;;

        -c | --desc ) # TODO
            echo description placeholder
            shift 2
            ;;

        -e | --editor ) # TODO
            echo open editor placeholder
            shift
            ;;

        -a | --assign_parent ) # TODO
            echo assign_parent placeholder
            shift 2
            ;;

        -p | --parent_selector ) # TODO
            echo parent_selector selector
            shift
            ;;

        -h | --help)
            help add
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

agenda() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help agenda
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help agenda
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

config() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help config
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help config
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

mark_done() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help mark_done
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help mark_done
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

edit() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help edit
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help edit
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

list() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help list
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help list
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

remove() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help remove
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help remove
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

view() {
    shift 

    SHORT=h # TODO implemented options
    LONG=help

    OPTS=$(getopt -n "$NAME" -o $SHORT -l $LONG -- "$@")
    if [ $? -ne -0 ]; then
        exit 1
    fi

    if [ "$#" -eq 0 ]; then
        help view
    fi

    eval set -- "$OPTS"

    while :; do
        case "$1" in # TODO implemented options

        -h | --help)
            help view
            ;;

        --)
            shift
            break
            ;;

        *)
            echo "ERROR: Invalid option, see help (-h, --help)" 
            exit 1   
            ;;

        esac
    done
}

# PARSE CLI
if [ "$#" -eq 0 ]; then
    default
fi


## Parse Modes
case "$1" in

    a | add ) 
        add "$@"
        ;;
    
    ag | agenda )
        agenda "$@"
        ;;

    c | config )
        config "$@"
        ;;

    d | done )
        mark_done "$@"
        ;;

    e | edit )
        edit "$@"
        ;;

    l | list )
        list "$@"
        ;;
    
    r | remove )
        remove "$@"
        ;;

    v | view )
        view "$@"
        ;;

    -h | --help )
        help
        ;;

    -v | --version )
        echo v$VERSION
        exit 0
        ;;

    * )
        echo "ERROR: Invalid mode, see help (-h, --help)" 
        exit 1       
esac
